#ifndef WOW_SOURCE_NET_NETCLIENT_NETCLIENT_H
#define WOW_SOURCE_NET_NETCLIENT_NETCLIENT_H

#include <stddef.h>
#include <storm.h>

#include "WowServices/WowConnection.h"

class CDataStore;
class ClntObjMgr;
class NetClientRedirect;
class NETEVENTQUEUE;
class WowConnection;
struct NETCONNADDR;

void ClientNetGetRealms(const char *serverAddress, void(*fcn)(CDataStore *, void *), void *userData);

enum NETSTATE {
  NS_UNINITIALIZED = 0,
  NS_INITIALIZING = 1,
  NS_INITIALIZED = 2,
  NS_REDIRECT_CONNECTING = 3,
  NS_GETTING_REALMS = 4,
  NS_CONNECTING = 5,
  NS_CONNECTED = 6,
  NS_DISCONNECTING = 7
};

enum NETMESSAGE {
  MSG_NULL_ACTION = 0,
  CMSG_BOOTME = 1,
  CMSG_DBLOOKUP = 2,
  SMSG_DBLOOKUP = 3,
  CMSG_QUERY_OBJECT_POSITION = 4,
  SMSG_QUERY_OBJECT_POSITION = 5,
  CMSG_QUERY_OBJECT_ROTATION = 6,
  SMSG_QUERY_OBJECT_ROTATION = 7,
  CMSG_WORLD_TELEPORT = 8,
  CMSG_TELEPORT_TO_PLAYER = 9,
  CMSG_ZONE_MAP = 10,
  SMSG_ZONE_MAP = 11,
  CMSG_DEBUG_CHANGECELLZONE = 12,
  CMSG_EMBLAZON_TABARD_OBSOLETE = 13,
  CMSG_UNEMBLAZON_TABARD_OBSOLETE = 14,
  CMSG_RECHARGE = 15,
  CMSG_LEARN_SPELL = 16,
  CMSG_CREATEMONSTER = 17,
  CMSG_DESTROYMONSTER = 18,
  CMSG_CREATEITEM = 19,
  CMSG_CREATEGAMEOBJECT = 20,
  CMSG_MAKEMONSTERATTACKME = 21,
  CMSG_MAKEMONSTERATTACKGUID = 22,
  CMSG_ENABLEDEBUGCOMBATLOGGING = 23,
  CMSG_FORCEACTION = 24,
  CMSG_FORCEACTIONONOTHER = 25,
  CMSG_FORCEACTIONSHOW = 26,
  SMSG_FORCEACTIONSHOW = 27,
  SMSG_ATTACKERSTATEUPDATEDEBUGINFO = 28,
  SMSG_ATTACKERSTATEUPDATEDEBUGINFOSPELL = 29,
  SMSG_ATTACKERSTATEUPDATEDEBUGINFOSPELLMISS = 30,
  SMSG_DEBUG_PLAYER_RANGE = 31,
  CMSG_UNDRESSPLAYER = 32,
  CMSG_BEASTMASTER = 33,
  CMSG_GODMODE = 34,
  SMSG_GODMODE = 35,
  CMSG_CHEAT_SETMONEY = 36,
  CMSG_LEVEL_CHEAT = 37,
  CMSG_PET_LEVEL_CHEAT = 38,
  CMSG_LEVELUP_CHEAT = 39,
  CMSG_COOLDOWN_CHEAT = 40,
  CMSG_USE_SKILL_CHEAT = 41,
  CMSG_FLAG_QUEST = 42,
  CMSG_FLAG_QUEST_FINISH = 43,
  CMSG_CLEAR_QUEST = 44,
  CMSG_SEND_EVENT = 45,
  CMSG_DEBUG_AISTATE = 46,
  SMSG_DEBUG_AISTATE = 47,
  CMSG_ENABLE_PVP = 48,
  CMSG_ADVANCE_SPAWN_TIME = 49,
  CMSG_PVP_PORT = 50,
  CMSG_AUTH_SRP6_BEGIN = 51,
  CMSG_AUTH_SRP6_PROOF = 52,
  CMSG_AUTH_SRP6_RECODE = 53,
  CMSG_CHAR_CREATE = 54,
  CMSG_CHAR_ENUM = 55,
  CMSG_CHAR_DELETE = 56,
  SMSG_AUTH_SRP6_RESPONSE = 57,
  SMSG_CHAR_CREATE = 58,
  SMSG_CHAR_ENUM = 59,
  SMSG_CHAR_DELETE = 60,
  CMSG_PLAYER_LOGIN = 61,
  SMSG_NEW_WORLD = 62,
  SMSG_TRANSFER_PENDING = 63,
  SMSG_TRANSFER_ABORTED = 64,
  SMSG_CHARACTER_LOGIN_FAILED = 65,
  SMSG_LOGIN_SETTIMESPEED = 66,
  SMSG_GAMETIME_UPDATE = 67,
  CMSG_GAMETIME_SET = 68,
  SMSG_GAMETIME_SET = 69,
  CMSG_GAMESPEED_SET = 70,
  SMSG_GAMESPEED_SET = 71,
  CMSG_SERVERTIME = 72,
  SMSG_SERVERTIME = 73,
  CMSG_PLAYER_LOGOUT = 74,
  CMSG_LOGOUT_REQUEST = 75,
  SMSG_LOGOUT_RESPONSE = 76,
  SMSG_LOGOUT_COMPLETE = 77,
  CMSG_LOGOUT_CANCEL = 78,
  SMSG_LOGOUT_CANCEL_ACK = 79,
  CMSG_NAME_QUERY = 80,
  SMSG_NAME_QUERY_RESPONSE = 81,
  CMSG_PET_NAME_QUERY = 82,
  SMSG_PET_NAME_QUERY_RESPONSE = 83,
  CMSG_GUILD_QUERY = 84,
  SMSG_GUILD_QUERY_RESPONSE = 85,
  CMSG_ITEM_QUERY_SINGLE = 86,
  CMSG_ITEM_QUERY_MULTIPLE = 87,
  SMSG_ITEM_QUERY_SINGLE_RESPONSE = 88,
  SMSG_ITEM_QUERY_MULTIPLE_RESPONSE = 89,
  CMSG_PAGE_TEXT_QUERY = 90,
  SMSG_PAGE_TEXT_QUERY_RESPONSE = 91,
  CMSG_QUEST_QUERY = 92,
  SMSG_QUEST_QUERY_RESPONSE = 93,
  CMSG_GAMEOBJECT_QUERY = 94,
  SMSG_GAMEOBJECT_QUERY_RESPONSE = 95,
  CMSG_CREATURE_QUERY = 96,
  SMSG_CREATURE_QUERY_RESPONSE = 97,
  CMSG_WHO = 98,
  SMSG_WHO = 99,
  CMSG_WHOIS = 100,
  SMSG_WHOIS = 101,
  CMSG_FRIEND_LIST = 102,
  SMSG_FRIEND_LIST = 103,
  SMSG_FRIEND_STATUS = 104,
  CMSG_ADD_FRIEND = 105,
  CMSG_DEL_FRIEND = 106,
  SMSG_IGNORE_LIST = 107,
  CMSG_ADD_IGNORE = 108,
  CMSG_DEL_IGNORE = 109,
  CMSG_GROUP_INVITE = 110,
  SMSG_GROUP_INVITE = 111,
  CMSG_GROUP_CANCEL = 112,
  SMSG_GROUP_CANCEL = 113,
  CMSG_GROUP_ACCEPT = 114,
  CMSG_GROUP_DECLINE = 115,
  SMSG_GROUP_DECLINE = 116,
  CMSG_GROUP_UNINVITE = 117,
  CMSG_GROUP_UNINVITE_GUID = 118,
  SMSG_GROUP_UNINVITE = 119,
  CMSG_GROUP_SET_LEADER = 120,
  SMSG_GROUP_SET_LEADER = 121,
  CMSG_LOOT_METHOD = 122,
  CMSG_GROUP_DISBAND = 123,
  SMSG_GROUP_DESTROYED = 124,
  SMSG_GROUP_LIST = 125,
  SMSG_PARTY_MEMBER_STATS = 126,
  SMSG_PARTY_COMMAND_RESULT = 127,
  UMSG_UPDATE_GROUP_MEMBERS = 128,
  CMSG_GUILD_CREATE = 129,
  CMSG_GUILD_INVITE = 130,
  SMSG_GUILD_INVITE = 131,
  CMSG_GUILD_ACCEPT = 132,
  CMSG_GUILD_DECLINE = 133,
  SMSG_GUILD_DECLINE = 134,
  CMSG_GUILD_INFO = 135,
  SMSG_GUILD_INFO = 136,
  CMSG_GUILD_ROSTER = 137,
  SMSG_GUILD_ROSTER = 138,
  CMSG_GUILD_PROMOTE = 139,
  CMSG_GUILD_DEMOTE = 140,
  CMSG_GUILD_LEAVE = 141,
  CMSG_GUILD_REMOVE = 142,
  CMSG_GUILD_DISBAND = 143,
  CMSG_GUILD_LEADER = 144,
  CMSG_GUILD_MOTD = 145,
  SMSG_GUILD_EVENT = 146,
  SMSG_GUILD_COMMAND_RESULT = 147,
  UMSG_UPDATE_GUILD = 148,
  CMSG_MESSAGECHAT = 149,
  SMSG_MESSAGECHAT = 150,
  CMSG_JOIN_CHANNEL = 151,
  CMSG_LEAVE_CHANNEL = 152,
  SMSG_CHANNEL_NOTIFY = 153,
  CMSG_CHANNEL_LIST = 154,
  SMSG_CHANNEL_LIST = 155,
  CMSG_CHANNEL_PASSWORD = 156,
  CMSG_CHANNEL_SET_OWNER = 157,
  CMSG_CHANNEL_OWNER = 158,
  CMSG_CHANNEL_MODERATOR = 159,
  CMSG_CHANNEL_UNMODERATOR = 160,
  CMSG_CHANNEL_MUTE = 161,
  CMSG_CHANNEL_UNMUTE = 162,
  CMSG_CHANNEL_INVITE = 163,
  CMSG_CHANNEL_KICK = 164,
  CMSG_CHANNEL_BAN = 165,
  CMSG_CHANNEL_UNBAN = 166,
  CMSG_CHANNEL_ANNOUNCEMENTS = 167,
  CMSG_CHANNEL_MODERATE = 168,
  SMSG_UPDATE_OBJECT = 169,
  SMSG_DESTROY_OBJECT = 170,
  CMSG_USE_ITEM = 171,
  CMSG_OPEN_ITEM = 172,
  CMSG_READ_ITEM = 173,
  SMSG_READ_ITEM_OK = 174,
  SMSG_READ_ITEM_FAILED = 175,
  SMSG_ITEM_COOLDOWN = 176,
  CMSG_GAMEOBJ_USE = 177,
  CMSG_GAMEOBJ_CHAIR_USE_OBSOLETE = 178,
  SMSG_GAMEOBJECT_CUSTOM_ANIM = 179,
  CMSG_AREATRIGGER = 180,
  MSG_MOVE_START_FORWARD = 181,
  MSG_MOVE_START_BACKWARD = 182,
  MSG_MOVE_STOP = 183,
  MSG_MOVE_START_STRAFE_LEFT = 184,
  MSG_MOVE_START_STRAFE_RIGHT = 185,
  MSG_MOVE_STOP_STRAFE = 186,
  MSG_MOVE_JUMP = 187,
  MSG_MOVE_START_TURN_LEFT = 188,
  MSG_MOVE_START_TURN_RIGHT = 189,
  MSG_MOVE_STOP_TURN = 190,
  MSG_MOVE_START_PITCH_UP = 191,
  MSG_MOVE_START_PITCH_DOWN = 192,
  MSG_MOVE_STOP_PITCH = 193,
  MSG_MOVE_SET_RUN_MODE = 194,
  MSG_MOVE_SET_WALK_MODE = 195,
  MSG_MOVE_TOGGLE_LOGGING = 196,
  MSG_MOVE_TELEPORT = 197,
  MSG_MOVE_TELEPORT_CHEAT = 198,
  MSG_MOVE_TELEPORT_ACK = 199,
  MSG_MOVE_TOGGLE_FALL_LOGGING = 200,
  MSG_MOVE_COLLIDE_REDIRECT = 201,
  MSG_MOVE_COLLIDE_STUCK = 202,
  MSG_MOVE_START_SWIM = 203,
  MSG_MOVE_STOP_SWIM = 204,
  MSG_MOVE_SET_RUN_SPEED_CHEAT = 205,
  MSG_MOVE_SET_RUN_SPEED = 206,
  MSG_MOVE_SET_WALK_SPEED_CHEAT = 207,
  MSG_MOVE_SET_WALK_SPEED = 208,
  MSG_MOVE_SET_SWIM_SPEED_CHEAT = 209,
  MSG_MOVE_SET_SWIM_SPEED = 210,
  MSG_MOVE_SET_ALL_SPEED_CHEAT = 211,
  MSG_MOVE_SET_TURN_RATE_CHEAT = 212,
  MSG_MOVE_SET_TURN_RATE = 213,
  MSG_MOVE_TOGGLE_COLLISION_CHEAT = 214,
  MSG_MOVE_SET_FACING = 215,
  MSG_MOVE_SET_PITCH = 216,
  MSG_MOVE_WORLDPORT_ACK = 217,
  SMSG_MONSTER_MOVE = 218,
  MSG_MOVE_RESERVED_0 = 219,
  MSG_MOVE_RESERVED_1 = 220,
  MSG_MOVE_RESERVED_2 = 221,
  MSG_MOVE_RESERVED_3 = 222,
  SMSG_FORCE_SPEED_CHANGE = 223,
  CMSG_FORCE_SPEED_CHANGE_ACK = 224,
  SMSG_FORCE_SWIM_SPEED_CHANGE = 225,
  CMSG_FORCE_SWIM_SPEED_CHANGE_ACK = 226,
  SMSG_FORCE_MOVE_ROOT = 227,
  CMSG_FORCE_MOVE_ROOT_ACK = 228,
  SMSG_FORCE_MOVE_UNROOT = 229,
  CMSG_FORCE_MOVE_UNROOT_ACK = 230,
  MSG_MOVE_ROOT = 231,
  MSG_MOVE_UNROOT = 232,
  MSG_MOVE_HEARTBEAT = 233,
  CMSG_STUCK_OBSOLETE = 234,
  CMSG_TRIGGER_CINEMATIC_CHEAT = 235,
  CMSG_OPENING_CINEMATIC = 236,
  SMSG_TRIGGER_CINEMATIC = 237,
  CMSG_NEXT_CINEMATIC_CAMERA = 238,
  CMSG_COMPLETE_CINEMATIC = 239,
  SMSG_TUTORIAL_FLAGS = 240,
  CMSG_TUTORIAL_SHOWN = 241,
  CMSG_TUTORIAL_CLEAR = 242,
  CMSG_TUTORIAL_RESET = 243,
  CMSG_STANDSTATECHANGE = 244,
  CMSG_EMOTE = 245,
  SMSG_EMOTE = 246,
  CMSG_TEXT_EMOTE = 247,
  SMSG_TEXT_EMOTE = 248,
  CMSG_AUTOEQUIP_GROUND_ITEM = 249,
  CMSG_AUTOSTORE_GROUND_ITEM = 250,
  CMSG_AUTOSTORE_LOOT_ITEM = 251,
  CMSG_STORE_LOOT_IN_SLOT = 252,
  CMSG_AUTOEQUIP_ITEM = 253,
  CMSG_AUTOSTORE_BAG_ITEM = 254,
  CMSG_SWAP_ITEM = 255,
  CMSG_SWAP_INV_ITEM = 256,
  CMSG_SPLIT_ITEM = 257,
  CMSG_PICKUP_ITEM = 258,
  CMSG_DROP_ITEM = 259,
  CMSG_DESTROYITEM = 260,
  SMSG_INVENTORY_CHANGE_FAILURE = 261,
  SMSG_OPEN_CONTAINER = 262,
  CMSG_INSPECT = 263,
  SMSG_INSPECT = 264,
  CMSG_INITIATE_TRADE = 265,
  CMSG_BEGIN_TRADE = 266,
  CMSG_BUSY_TRADE = 267,
  CMSG_IGNORE_TRADE = 268,
  CMSG_ACCEPT_TRADE = 269,
  CMSG_UNACCEPT_TRADE = 270,
  CMSG_CANCEL_TRADE = 271,
  CMSG_SET_TRADE_ITEM = 272,
  CMSG_CLEAR_TRADE_ITEM = 273,
  CMSG_SET_TRADE_GOLD = 274,
  SMSG_TRADE_STATUS = 275,
  SMSG_TRADE_STATUS_EXTENDED = 276,
  SMSG_INITIALIZE_FACTIONS = 277,
  SMSG_SET_FACTION_VISIBLE = 278,
  SMSG_SET_FACTION_STANDING = 279,
  CMSG_SET_FACTION_ATWAR = 280,
  CMSG_SET_FACTION_CHEAT = 281,
  SMSG_SET_PROFICIENCY = 282,
  CMSG_SET_ACTION_BUTTON = 283,
  SMSG_ACTION_BUTTONS = 284,
  SMSG_INITIAL_SPELLS = 285,
  SMSG_LEARNED_SPELL = 286,
  SMSG_SUPERCEDED_SPELL = 287,
  CMSG_NEW_SPELL_SLOT = 288,
  CMSG_CAST_SPELL = 289,
  CMSG_CANCEL_CAST = 290,
  SMSG_CAST_RESULT = 291,
  SMSG_SPELL_START = 292,
  SMSG_SPELL_GO = 293,
  SMSG_SPELL_FAILURE = 294,
  SMSG_SPELL_COOLDOWN = 295,
  SMSG_COOLDOWN_EVENT = 296,
  CMSG_CANCEL_AURA = 297,
  SMSG_UPDATE_AURA_DURATION = 298,
  SMSG_PET_CAST_FAILED = 299,
  MSG_CHANNEL_START = 300,
  MSG_CHANNEL_UPDATE = 301,
  CMSG_CANCEL_CHANNELLING = 302,
  SMSG_AI_REACTION = 303,
  CMSG_SET_SELECTION = 304,
  CMSG_SET_TARGET = 305,
  CMSG_START_USING_RANGED_WEAPON = 306,
  CMSG_STOP_USING_RANGED_WEAPON = 307,
  CMSG_ATTACKSWING = 308,
  CMSG_ATTACKSTOP = 309,
  SMSG_ATTACKSTART = 310,
  SMSG_ATTACKSTOP = 311,
  SMSG_ATTACKSWING_NOTINRANGE = 312,
  SMSG_ATTACKSWING_BADFACING = 313,
  SMSG_ATTACKSWING_NOTSTANDING = 314,
  SMSG_ATTACKSWING_DEADTARGET = 315,
  SMSG_ATTACKSWING_CANT_ATTACK = 316,
  SMSG_ATTACKERSTATEUPDATE = 317,
  SMSG_VICTIMSTATEUPDATE_OBSOLETE = 318,
  SMSG_DAMAGE_DONE = 319,
  SMSG_DAMAGE_TAKEN = 320,
  SMSG_CANCEL_COMBAT = 321,
  SMSG_PLAYER_COMBAT_XP_GAIN_OBSOLETE = 322,
  SMSG_HEALSPELL_ON_PLAYER = 323,
  SMSG_HEALSPELL_ON_PLAYERS_PET = 324,
  CMSG_SHEATHE = 325,
  CMSG_SAVE_PLAYER = 326,
  CMSG_SETDEATHBINDPOINT = 327,
  SMSG_BINDPOINTUPDATE = 328,
  CMSG_GETDEATHBINDZONE = 329,
  SMSG_BINDZONEREPLY = 330,
  SMSG_PLAYERBOUND = 331,
  SMSG_DEATH_NOTIFY = 332,
  CMSG_REPOP_REQUEST = 333,
  SMSG_RESURRECT_REQUEST = 334,
  CMSG_RESURRECT_RESPONSE = 335,
  CMSG_LOOT = 336,
  CMSG_LOOT_MONEY = 337,
  CMSG_LOOT_RELEASE = 338,
  SMSG_LOOT_RESPONSE = 339,
  SMSG_LOOT_RELEASE_RESPONSE = 340,
  SMSG_LOOT_REMOVED = 341,
  SMSG_LOOT_MONEY_NOTIFY = 342,
  SMSG_LOOT_ITEM_NOTIFY = 343,
  SMSG_LOOT_CLEAR_MONEY = 344,
  SMSG_ITEM_PUSH_RESULT = 345,
  SMSG_DUEL_REQUESTED = 346,
  SMSG_DUEL_OUTOFBOUNDS = 347,
  SMSG_DUEL_INBOUNDS = 348,
  SMSG_DUEL_COMPLETE = 349,
  SMSG_DUEL_WINNER = 350,
  CMSG_DUEL_ACCEPTED = 351,
  CMSG_DUEL_CANCELLED = 352,
  SMSG_MOUNTRESULT = 353,
  SMSG_DISMOUNTRESULT = 354,
  SMSG_PUREMOUNT_CANCELLED = 355,
  CMSG_MOUNTSPECIAL_ANIM = 356,
  SMSG_MOUNTSPECIAL_ANIM = 357,
  SMSG_PET_TAME_FAILURE = 358,
  CMSG_PET_SET_ACTION = 359,
  CMSG_PET_ACTION = 360,
  CMSG_PET_ABANDON = 361,
  CMSG_PET_RENAME = 362,
  SMSG_PET_NAME_INVALID = 363,
  SMSG_PET_SPELLS = 364,
  CMSG_PET_CAST_SPELL_OBSOLETE = 365,
  CMSG_LIST_INVENTORY = 366,
  SMSG_LIST_INVENTORY = 367,
  CMSG_SELL_ITEM = 368,
  SMSG_SELL_ITEM = 369,
  CMSG_BUY_ITEM = 370,
  CMSG_BUY_ITEM_IN_SLOT = 371,
  SMSG_BUY_ITEM = 372,
  SMSG_BUY_FAILED = 373,
  CMSG_NPC_HELLO = 374,
  SMSG_NPC_HYPERTEXT = 375,
  CMSG_NPC_TEXT_QUERY = 376,
  SMSG_NPC_TEXT_UPDATE = 377,
  CMSG_NPC_OFFER_ITEM = 378,
  SMSG_NPC_ACCEPT_ITEM = 379,
  SMSG_NPC_DECLINE_ITEM = 380,
  SMSG_NPC_WONT_TALK = 381,
  CMSG_QUESTGIVER_STATUS_QUERY = 382,
  SMSG_QUESTGIVER_STATUS = 383,
  CMSG_QUESTGIVER_HELLO = 384,
  SMSG_QUESTGIVER_QUEST_LIST = 385,
  CMSG_QUESTGIVER_QUERY_QUEST = 386,
  CMSG_QUESTGIVER_QUEST_AUTOLAUNCH = 387,
  SMSG_QUESTGIVER_QUEST_DETAILS = 388,
  CMSG_QUESTGIVER_ACCEPT_QUEST = 389,
  CMSG_QUESTGIVER_COMPLETE_QUEST = 390,
  SMSG_QUESTGIVER_REQUEST_ITEMS = 391,
  CMSG_QUESTGIVER_REQUEST_REWARD = 392,
  SMSG_QUESTGIVER_OFFER_REWARD = 393,
  CMSG_QUESTGIVER_CHOOSE_REWARD = 394,
  SMSG_QUESTGIVER_QUEST_INVALID = 395,
  CMSG_QUESTGIVER_CANCEL = 396,
  SMSG_QUESTGIVER_QUEST_COMPLETE = 397,
  SMSG_QUESTGIVER_QUEST_FAILED = 398,
  CMSG_QUESTLOG_SWAP_QUEST = 399,
  CMSG_QUESTLOG_REMOVE_QUEST = 400,
  SMSG_QUESTLOG_FULL = 401,
  SMSG_QUESTUPDATE_FAILED = 402,
  SMSG_QUESTUPDATE_COMPLETE = 403,
  SMSG_QUESTUPDATE_ADD_KILL = 404,
  SMSG_QUESTUPDATE_ADD_ITEM = 405,
  CMSG_QUEST_CONFIRM_ACCEPT = 406,
  SMSG_QUEST_CONFIRM_ACCEPT = 407,
  CMSG_TAXICLEARALLNODES = 408,
  CMSG_TAXIENABLEALLNODES = 409,
  CMSG_TAXISHOWNODES = 410,
  SMSG_SHOWTAXINODES = 411,
  CMSG_TAXINODE_STATUS_QUERY = 412,
  SMSG_TAXINODE_STATUS = 413,
  CMSG_TAXIQUERYAVAILABLENODES = 414,
  CMSG_ACTIVATETAXI = 415,
  SMSG_ACTIVATETAXIREPLY = 416,
  SMSG_NEW_TAXI_PATH = 417,
  CMSG_TRAINER_LIST = 418,
  SMSG_TRAINER_LIST = 419,
  CMSG_TRAINER_BUY_SPELL = 420,
  SMSG_TRAINER_BUY_SUCCEEDED = 421,
  SMSG_TRAINER_BUY_FAILED = 422,
  CMSG_BINDER_ACTIVATE = 423,
  SMSG_PLAYERBINDERROR = 424,
  CMSG_BANKER_ACTIVATE = 425,
  SMSG_SHOW_BANK = 426,
  CMSG_BUY_BANK_SLOT = 427,
  SMSG_BUY_BANK_SLOT_RESULT = 428,
  CMSG_PETITION_SHOWLIST = 429,
  SMSG_PETITION_SHOWLIST = 430,
  CMSG_PETITION_BUY = 431,
  CMSG_PETITION_SHOW_SIGNATURES = 432,
  SMSG_PETITION_SHOW_SIGNATURES = 433,
  CMSG_PETITION_SIGN = 434,
  SMSG_PETITION_SIGN_RESULTS = 435,
  CMSG_OFFER_PETITION = 436,
  CMSG_TURN_IN_PETITION = 437,
  SMSG_TURN_IN_PETITION_RESULTS = 438,
  CMSG_PETITION_QUERY = 439,
  SMSG_PETITION_QUERY_RESPONSE = 440,
  SMSG_FISH_NOT_HOOKED = 441,
  SMSG_FISH_ESCAPED = 442,
  CMSG_BUG = 443,
  SMSG_NOTIFICATION = 444,
  CMSG_PLAYED_TIME = 445,
  SMSG_PLAYED_TIME = 446,
  CMSG_QUERY_TIME = 447,
  SMSG_QUERY_TIME_RESPONSE = 448,
  SMSG_LOG_XPGAIN = 449,
  MSG_SPLIT_MONEY = 450,
  CMSG_RECLAIM_CORPSE = 451,
  CMSG_WRAP_ITEM = 452,
  SMSG_LEVELUP_INFO = 453,
  MSG_MINIMAP_PING = 454,
  SMSG_RESISTLOG = 455,
  SMSG_ENCHANTMENTLOG = 456,
  CMSG_SET_SKILL_CHEAT = 457,
  SMSG_START_MIRROR_TIMER = 458,
  SMSG_PAUSE_MIRROR_TIMER = 459,
  SMSG_STOP_MIRROR_TIMER = 460,
  CMSG_PING = 461,
  SMSG_PONG = 462,
  SMSG_CLEAR_COOLDOWN = 463,
  SMSG_GAMEOBJECT_PAGETEXT = 464,
  CMSG_SETWEAPONMODE = 465,
  SMSG_COOLDOWN_CHEAT = 466,
  SMSG_SPELL_DELAYED = 467,
  CMSG_PLAYER_MACRO = 468,
  SMSG_PLAYER_MACRO = 469,
  CMSG_GHOST = 470,
  CMSG_GM_INVIS = 471,
  CMSG_SCREENSHOT = 472,
  MSG_GM_BIND_OTHER = 473,
  MSG_GM_SUMMON = 474,
  SMSG_ITEM_TIME_UPDATE = 475,
  SMSG_ITEM_ENCHANT_TIME_UPDATE = 476,
  SMSG_AUTH_CHALLENGE = 477,
  CMSG_AUTH_SESSION = 478,
  SMSG_AUTH_RESPONSE = 479,
  MSG_GM_SHOWLABEL = 480,
  MSG_ADD_DYNAMIC_TARGET = 481,
  MSG_SAVE_GUILD_EMBLEM = 482,
  MSG_TABARDVENDOR_ACTIVATE = 483,
  SMSG_PLAY_SPELL_VISUAL = 484,
  CMSG_ZONEUPDATE = 485,
  SMSG_PARTYKILLLOG = 486,
  SMSG_COMPRESSED_UPDATE_OBJECT = 487,
  SMSG_MIRRORTIMERDAMAGELOG = 488,
  SMSG_EXPLORATION_EXPERIENCE = 489,
  CMSG_GM_SET_SECURITY_GROUP = 490,
  CMSG_GM_NUKE = 491,
  MSG_RANDOM_ROLL = 492,
  SMSG_ENVIRONMENTALDAMAGELOG = 493,
  CMSG_RWHOIS = 494,
  SMSG_RWHOIS = 495,
  MSG_LOOKING_FOR_GROUP = 496,
  CMSG_SET_LOOKING_FOR_GROUP = 497,
  NUM_MSG_TYPES = 498
};

class NetClient : public WowConnectionResponse {
 public:
  NetClient();
  NetClient(const NetClient &client);
  virtual ~NetClient();

  NetClient &operator=(const NetClient &client);

  virtual int  Initialize();
  virtual void Destroy();
  virtual int  DelayedDelete();

  void Connect(const char *hostName);
  void Disconnect();
  void Send(CDataStore *msg);
  void SetMessageHandler(NETMESSAGE msgId, int(*handler)(void *, NETMESSAGE, unsigned long, CDataStore *), void *param);
  void ClearMessageHandler(NETMESSAGE msgId);

  NETSTATE GetState() {
    return m_netState;
  }

  void HandleIdle();

  virtual int HandleData(unsigned long timeReceived, void *data, int size);
  virtual int HandleConnect();
  virtual int HandleDisconnect();
  virtual int HandleCantConnect();

  void AddRef() {
    long newval = SInterlockedIncrement((long *)&m_refCount);
    ASSERT(newval > 0);
  }

  void DelRef() {
    long newval = SInterlockedDecrement((long *)&m_refCount);
    ASSERT(newval >= 0);
    if (!newval && m_deleteMe) {
      DEL(this);
    }
  }

  void SetDelete() {
    m_deleteMe = 1;
  }

  unsigned char GetDelete() {
    return m_deleteMe;
  }

  void GetNetStats(float &bandwidthIn, float &bandwidthOut, unsigned long &latency);

  void SetObjMgr(ClntObjMgr *objMgr) {
    m_objMgr = objMgr;
  }

  void         PollEventQueue();
  unsigned int GetAddr();

 private:
  friend class NetClientRedirect;

  static int __stdcall ClientRedirectEventHandler(
      HNETCONN__        *conn,
      const NETCONNADDR *connAddr,
      NETNOTE            note,
      void              *user,
      const void        *data,
      unsigned long      bytes,
      unsigned long     *bytesProcessed
  );

  int  Connect(const char *hostName, unsigned short port);
  void CancelRedirect();
  void ProcessMessage(unsigned long timeStamp, CDataStore *msg);
  void PushObjMgr();
  void PopObjMgr();
  void PongHandler(CDataStore *msg);
  void Ping();
  void DisplayNetworkStats();

  virtual void WCMessageReady(WowConnection *conn, unsigned long timeStamp, CDataStore *msg);
  virtual void WCConnected(WowConnection *conn, WowConnection *inbound, unsigned long timeStamp, const NETCONNADDR *addr);
  virtual void WCCantConnect(WowConnection *conn, unsigned long timeStamp, const NETCONNADDR *addr);
  virtual void WCDisconnected(WowConnection *conn, unsigned long timeStamp, const NETCONNADDR *addr);

  static int s_clientCount;

  NetClient **m_redirectHandle;
  int         m_redirectBytesRead;
  char        m_redirectHostPort[0x401];
  NETSTATE    m_netState;
  int(*m_handlers[NUM_MSG_TYPES])(void *, NETMESSAGE, unsigned long, CDataStore *);
  void              *m_handlerParams[NUM_MSG_TYPES];
  NETEVENTQUEUE     *m_netEventQueue;
  WowConnection     *m_serverConnection;
  int                m_refCount;
  unsigned char      m_deleteMe;
  unsigned long      m_pingSent;
  unsigned long      m_pingSequence;
  unsigned long      m_latency[16];
  unsigned long      m_latencyStart;
  unsigned long      m_latencyEnd;
  unsigned long      m_bytesSent;
  unsigned long      m_bytesReceived;
  unsigned long      m_connectedTimestamp;
  SCritSect          m_pingLock;
  ClntObjMgr        *m_objMgr;
  ClntObjMgr        *m_saveObjMgr;
  NetClientRedirect *m_redirect;
};

#endif
