#ifndef ENGINE_SOURCE_OS_W32_OSTCP_H
#define ENGINE_SOURCE_OS_W32_OSTCP_H

#ifndef INCL_WINSOCK_API_TYPEDEFS
#define INCL_WINSOCK_API_TYPEDEFS 1
#endif
#include <winsock2.h>
#include <mswsock.h>

#include <Base/Base.h>

#include "Os/OsNet.h"

#include <stpl.h>

#include <W32/ISThread.h>

namespace OsNet {

  extern LPCSTR OSNETERR_INTERNAL;
  extern LPCSTR OSNETERR_WINSOCKSTARTUP;
  extern LPCSTR OSNETERR_WINSOCKVERSION;
  extern LPCSTR OSNETERR_SENDFAILED;
  extern LPCSTR OSNETERR_THREADFAILED;
  extern LPCSTR OSNETERR_EVENTFAILED;
  extern LPCSTR OSNETERR_BINDFAILED;
  extern LPCSTR OSNETERR_LISTENFAILED;
  extern LPCSTR OSNETERR_SOCKETFAILED;
  extern LPCSTR OSNETERR_SELECTFAILED;
  extern LPCSTR OSNETERR_ACCEPTFAILED;
  extern LPCSTR OSNETERR_PORTFAILED;
  extern LPCSTR OSNETERR_OVERLAPTYPE;
  extern LPCSTR OSNETERR_LISTENCLOSED;
  extern LPCSTR OSNETERR_ACCEPTEXFAILED;

}  // namespace OsNet

#endif
