add_subdirectory(Source/Anim)
add_subdirectory(Source/Base)
add_subdirectory(Source/Event)
add_subdirectory(Source/Frame)
add_subdirectory(Source/MDLFile)
add_subdirectory(Source/Model)
if(WIN32)
    add_subdirectory(Source/Os)
endif()
add_subdirectory(Source/Scrn)
add_subdirectory(Source/Services)
add_subdirectory(Source/Tempest)
add_subdirectory(Source/Gx)
add_subdirectory(Source/Images)
add_subdirectory(Source/Gxu/FreeType)
add_subdirectory(Source/BLPFile)
add_subdirectory(Source/Gxu)
add_subdirectory(Source/SRP)
add_subdirectory(Source/Expat)
add_subdirectory(Source/FrameXML)
add_subdirectory(Source/lua)
add_subdirectory(Source/FrameScript)
add_subdirectory(Source/regex)
