#ifndef ENGINE_SOURCE_MDLFILE_PARSER_H
#define ENGINE_SOURCE_MDLFILE_PARSER_H

#include <Base/Base.h>

enum {
  MDLTOK_EOF = 0,
  MDLTOK_FIRST_TOKEN = 256,
  MDLTOK_LONG = 256,
  MDLTOK_FLOAT = 257,
  MDLTOK_STRING = 258,
  MDLTOK_VERSION = 259,
  MDLTOK_MODEL = 260,
  MDLTOK_SEQUENCES = 261,
  MDLTOK_GLOBALSEQUENCES = 262,
  MDLTOK_TEXTUREANIMS = 263,
  MDLTOK_TEXTURES = 264,
  MDLTOK_MATERIALS = 265,
  MDLTOK_GEOSET = 266,
  MDLTOK_GEOSETANIM = 267,
  MDLTOK_BONE = 268,
  MDLTOK_MESH = 269,
  MDLTOK_LIGHT = 270,
  MDLTOK_HELPER = 271,
  MDLTOK_ATTACHMENT = 272,
  MDLTOK_PIVOTPOINTS = 273,
  MDLTOK_PARTICLEEMITTER = 274,
  MDLTOK_PARTICLEEMITTER2 = 275,
  MDLTOK_CAMERA = 276,
  MDLTOK_EVENTOBJECT = 277,
  MDLTOK_HITTESTSHAPE = 278,
  MDLTOK_COLLISIONSHAPE = 279,
  MDLTOK_RIBBONEMITTER = 280,
  MDLTOK_COLLISION = 281,
  MDLTOK_ADDITIVE = 282,
  MDLTOK_ADD_ALPHA = 283,
  MDLTOK_ALPHA = 284,
  MDLTOK_ALPHA_KEY = 285,
  MDLTOK_ALWAYS_ANIMATE = 286,
  MDLTOK_AMB_COLOR = 287,
  MDLTOK_AMB_INTENSITY = 288,
  MDLTOK_AMBIENT = 289,
  MDLTOK_ANIM = 290,
  MDLTOK_ANIMATIONFILE = 291,
  MDLTOK_ATTACHMENTID = 292,
  MDLTOK_ATTENUATION = 293,
  MDLTOK_ATTENUATIONSTART = 294,
  MDLTOK_ATTENUATIONEND = 295,
  MDLTOK_BEZIER = 296,
  MDLTOK_BILLBOARD = 297,
  MDLTOK_BILLBOARD_LOCK_X = 298,
  MDLTOK_BILLBOARD_LOCK_Y = 299,
  MDLTOK_BILLBOARD_LOCK_Z = 300,
  MDLTOK_BITMAP = 301,
  MDLTOK_BLEND = 302,
  MDLTOK_BLEND_COLORS = 303,
  MDLTOK_BLEND_TIME = 304,
  MDLTOK_BONE_INDICES = 305,
  MDLTOK_BONE_WEIGHTS = 306,
  MDLTOK_BOTH = 307,
  MDLTOK_BOUNDS_RADIUS = 308,
  MDLTOK_BOX = 309,
  MDLTOK_COLOR = 310,
  MDLTOK_COLS = 311,
  MDLTOK_COMPONENT_SKIN = 312,
  MDLTOK_CONNECT = 313,
  MDLTOK_CONSTANTCOLOR = 314,
  MDLTOK_COORD_ID = 315,
  MDLTOK_CYLINDER = 316,
  MDLTOK_DECAY_UV = 317,
  MDLTOK_DIRECTIONAL = 318,
  MDLTOK_DONTINHERIT = 319,
  MDLTOK_DONTINTERP = 320,
  MDLTOK_DRAG = 321,
  MDLTOK_DUPLICATES = 322,
  MDLTOK_DURATION = 323,
  MDLTOK_EMISSION_RATE = 324,
  MDLTOK_EMITTER_USES_MDL = 325,
  MDLTOK_EMITTER_USES_TGA = 326,
  MDLTOK_EVENT_TRACK = 327,
  MDLTOK_FACES = 328,
  MDLTOK_FAR_CLIP = 329,
  MDLTOK_FIELDOFVIEW = 330,
  MDLTOK_FILTERMODE = 331,
  MDLTOK_FORMATVERSION = 332,
  MDLTOK_FPS = 333,
  MDLTOK_FREQUENCY = 334,
  MDLTOK_FULLRESOLUTION = 335,
  MDLTOK_GEOSETID = 336,
  MDLTOK_GEOSETANIMID = 337,
  MDLTOK_GLOBALSEQID = 338,
  MDLTOK_GRAVITY = 339,
  MDLTOK_GROUNDTRACK = 340,
  MDLTOK_GROUP = 341,
  MDLTOK_GROUPS = 342,
  MDLTOK_HEAD = 343,
  MDLTOK_HEIGHT = 344,
  MDLTOK_HEIGHT_ABOVE = 345,
  MDLTOK_HEIGHT_BELOW = 346,
  MDLTOK_HERMITE = 347,
  MDLTOK_IMAGE = 348,
  MDLTOK_INIT_VELOCITY = 349,
  MDLTOK_INTAN = 350,
  MDLTOK_INTENSITY = 351,
  MDLTOK_INTERVAL = 352,
  MDLTOK_LATITUDE = 353,
  MDLTOK_LONGITUDE = 354,
  MDLTOK_LAYER = 355,
  MDLTOK_LENGTH = 356,
  MDLTOK_LIFESPAN = 357,
  MDLTOK_LIFESPAN_UV = 358,
  MDLTOK_LINEAR = 359,
  MDLTOK_LINES = 360,
  MDLTOK_LINE_EMITTER = 361,
  MDLTOK_LINE_LOOP = 362,
  MDLTOK_LINE_STRIP = 363,
  MDLTOK_MATERIAL = 364,
  MDLTOK_MATERIAL_ID = 365,
  MDLTOK_MATRICES = 366,
  MDLTOK_MAXIMUMEXTENT = 367,
  MDLTOK_MINIMUMEXTENT = 368,
  MDLTOK_MODEL_SPACE = 369,
  MDLTOK_MODULATE = 370,
  MDLTOK_MODULATE2X = 371,
  MDLTOK_MOVESPEED = 372,
  MDLTOK_MULTIPLE = 373,
  MDLTOK_NEAR_CLIP = 374,
  MDLTOK_NO_DEPTH_TEST = 375,
  MDLTOK_NO_DEPTH_SET = 376,
  MDLTOK_CAPNONE = 377,
  MDLTOK_NONLOOPING = 378,
  MDLTOK_NORMALS = 379,
  MDLTOK_NUMATTACHMENTS = 380,
  MDLTOK_NUMBONES = 381,
  MDLTOK_NUMEVENTS = 382,
  MDLTOK_NUMGEOSETS = 383,
  MDLTOK_NUMGEOSETANIMS = 384,
  MDLTOK_NUMHELPERS = 385,
  MDLTOK_NUMLIGHTS = 386,
  MDLTOK_NUMMESHES = 387,
  MDLTOK_NUMPARTICLEEMITTERS = 388,
  MDLTOK_NUMPARTICLEEMITTERS2 = 389,
  MDLTOK_NUMRIBBONEMITTERS = 390,
  MDLTOK_OBJECTID = 391,
  MDLTOK_OMNIDIRECTIONAL = 392,
  MDLTOK_OPACITY = 393,
  MDLTOK_OUTTAN = 394,
  MDLTOK_PARENT = 395,
  MDLTOK_PARTICLE = 396,
  MDLTOK_PARTICLE_0XKILL = 397,
  MDLTOK_PARTICLE_EXTRUDE = 398,
  MDLTOK_PARTICLE_FOLLOW = 399,
  MDLTOK_PARTICLE_FOLLOW_PARAMS = 400,
  MDLTOK_PARTICLE_INHERIT_SCALE = 401,
  MDLTOK_PARTICLE_IVEL_LIN = 402,
  MDLTOK_PARTICLE_IVEL_SCALE = 403,
  MDLTOK_PARTICLE_GEOMETRY_MDL = 404,
  MDLTOK_PARTICLE_PROJECT = 405,
  MDLTOK_PARTICLE_RECURSION_MDL = 406,
  MDLTOK_PARTICLE_ROTATION = 407,
  MDLTOK_PARTICLE_SCALING = 408,
  MDLTOK_PARTICLE_TUMBLE = 409,
  MDLTOK_PARTICLE_TUMBLER = 410,
  MDLTOK_PARTICLE_TWINKLE_ONOFF = 411,
  MDLTOK_PARTICLE_TWINKLE_SCALE = 412,
  MDLTOK_PARTICLE_XYQUADS = 413,
  MDLTOK_PARTICLE_ZSOURCE = 414,
  MDLTOK_PARTICLE_ZVEL_ONLY = 415,
  MDLTOK_PATH = 416,
  MDLTOK_PITCH = 417,
  MDLTOK_PLANE = 418,
  MDLTOK_POINTS = 419,
  MDLTOK_POLYGON = 420,
  MDLTOK_POSITION = 421,
  MDLTOK_PRIORITYPLANE = 422,
  MDLTOK_PROJECT = 423,
  MDLTOK_QUADS = 424,
  MDLTOK_QUAD_STRIP = 425,
  MDLTOK_REPLACEABLE_ID = 426,
  MDLTOK_REPLAY = 427,
  MDLTOK_ROLL = 428,
  MDLTOK_ROTATION = 429,
  MDLTOK_ROWS = 430,
  MDLTOK_SCALING = 431,
  MDLTOK_SEGMENT_COLOR = 432,
  MDLTOK_SELECTION_GROUP = 433,
  MDLTOK_SNDMAXDIST = 434,
  MDLTOK_SNDMINDIST = 435,
  MDLTOK_SPHERE = 436,
  MDLTOK_SPHERE_ENV_MAP = 437,
  MDLTOK_SPLINE = 438,
  MDLTOK_SORTPRIMSFARZ = 439,
  MDLTOK_SORTPRIMSNEARZ = 440,
  MDLTOK_SPEED = 441,
  MDLTOK_SQUIRT = 442,
  MDLTOK_STATIC = 443,
  MDLTOK_TAIL = 444,
  MDLTOK_TAIL_GROWS = 445,
  MDLTOK_TAIL_LENGTH = 446,
  MDLTOK_TAIL_DECAY_UV = 447,
  MDLTOK_TAIL_UV = 448,
  MDLTOK_TARGET = 449,
  MDLTOK_TEAM_COLOR = 450,
  MDLTOK_TEXTURE_ID = 451,
  MDLTOK_TEXTURE_SLOT = 452,
  MDLTOK_TFACES = 453,
  MDLTOK_TIME = 454,
  MDLTOK_TRANSLATION = 455,
  MDLTOK_TRANSPARENT = 456,
  MDLTOK_TRIANGLES = 457,
  MDLTOK_TRIANGLE_FAN = 458,
  MDLTOK_TRIANGLE_STRIP = 459,
  MDLTOK_TVERTEXANIM = 460,
  MDLTOK_TVERTEXANIMID = 461,
  MDLTOK_TVERTICES = 462,
  MDLTOK_TWO_SIDED = 463,
  MDLTOK_TYPE = 464,
  MDLTOK_UNFOGGED = 465,
  MDLTOK_UNSELECTABLE = 466,
  MDLTOK_UNSHADED = 467,
  MDLTOK_VARIATION = 468,
  MDLTOK_VERTEX = 469,
  MDLTOK_VERTEXCOUNT = 470,
  MDLTOK_VERTEX_GROUP = 471,
  MDLTOK_VERTICES = 472,
  MDLTOK_VISIBILITY = 473,
  MDLTOK_WIDTH = 474,
  MDLTOK_WIND = 475,
  MDLTOK_WRAPHEIGHT = 476,
  MDLTOK_WRAPWIDTH = 477,
  MDLTOK_YAW = 478,
  MDLTOK_UNKNOWN = 479,
  MDLTOK_LAST_TOKEN = 480,
  MDLTOK_LEX_FATAL = -2
};

class CMDLStatus;
class mdl_scan;
union UTokenData {
  char  cVal;
  long  lVal;
  float fVal;
  char *sVal;
};

class Parser {
 public:
  Parser(CMDLStatus *status, mdl_scan &scanner) : m_scanner(scanner), m_status(status), m_flags(0) {
  }

  void   FatalDuplicate(LPCSTR found);
  void   FatalUnmatched(LPCSTR item1, UINT count1, LPCSTR item2, UINT count2);
  void   FatalNotFound(LPCSTR expected);
  void   FatalNotFound(UINT what);
  void   FatalUnexpected(LPCSTR found);
  void   FatalExpected(LPCSTR expected, LPCSTR found);
  void   FatalExpected(UINT what, LPCSTR found);
  void   FatalEOF();
  void   WarningCount(LPCSTR item, long expected, long actual);
  BOOL   FoundError() {
    return m_flags & 1;
  }
  void   Expect(UINT what);
  void   Expect(UINT what, UINT cachedToken, LPCSTR tokenText);
  long   ExpectInt();
  long   ExpectInt(UINT cachedToken, LPCSTR tokenText, UTokenData *cachedValue);
  float  ExpectFloat();
  LPCSTR ExpectString();
  LPCSTR ExpectString(UINT cachedToken, LPCSTR tokenText, UTokenData *cachedValue);
  long   GetOptionalInt(UINT *token, LPCSTR *tokenText, UTokenData *savedValue);
  long   GetOptionalInt(UINT cachedToken, UTokenData *cachedValue, UINT *token, LPCSTR *tokenText);
  BOOL   GetOptionalToken(UINT expected, UINT *token, LPCSTR *tokenText);
  BOOL   GetOptionalToken(UINT expected, UINT cachedToken, UINT *token, LPCSTR *tokenText);
  UINT   Token(LPCSTR *tokenText, UTokenData *data);
  int    GetLineNumber();

 private:
  Parser &operator=(const Parser &);

  mdl_scan   &m_scanner;
  CMDLStatus *m_status;
  UINT        m_flags;
};

#endif
