#include <Base/Base.h>
#include "Parser.h"

static const struct {
  UINT   token;
  LPCSTR text;
} s_tokentext[224] = {
      {MDLTOK_LONG,         "Literal Long"},
      {MDLTOK_FLOAT,        "Literal Float"},
      {MDLTOK_STRING,       "Literal String"},
      {MDLTOK_VERSION,              "Version"},
      {MDLTOK_MODEL,                "Model"},
      {MDLTOK_SEQUENCES,            "Sequences"},
      {MDLTOK_GLOBALSEQUENCES,      "GlobalSequences"},
      {MDLTOK_TEXTUREANIMS,         "TextureAnims"},
      {MDLTOK_TEXTURES,             "Textures"},
      {MDLTOK_MATERIALS,            "Materials"},
      {MDLTOK_GEOSET,               "Geoset"},
      {MDLTOK_GEOSETANIM,           "GeosetAnim"},
      {MDLTOK_BONE,                 "Bone"},
      {MDLTOK_MESH,                 "Mesh"},
      {MDLTOK_LIGHT,                "Light"},
      {MDLTOK_HELPER,               "Helper"},
      {MDLTOK_ATTACHMENT,           "Attachment"},
      {MDLTOK_PIVOTPOINTS,          "PivotPoints"},
      {MDLTOK_PARTICLEEMITTER,      "ParticleEmitter"},
      {MDLTOK_PARTICLEEMITTER2,     "ParticleEmitter2"},
      {MDLTOK_CAMERA,               "Camera"},
      {MDLTOK_EVENTOBJECT,          "EventObject"},
      {MDLTOK_HITTESTSHAPE,         "HitTestShape"},
      {MDLTOK_COLLISIONSHAPE,       "CollisionShape"},
      {MDLTOK_RIBBONEMITTER,        "RibbonEmitter"},
      {MDLTOK_COLLISION,            "Collision"},
      {MDLTOK_ADDITIVE,             "Additive"},
      {MDLTOK_ADD_ALPHA,             "AddAlpha"},
      {MDLTOK_ALPHA,                "Alpha"},
      {MDLTOK_ALPHA_KEY,             "AlphaKey"},
      {MDLTOK_ALWAYS_ANIMATE,        "AlwaysAnimate"},
      {MDLTOK_AMB_COLOR,             "AmbColor"},
      {MDLTOK_AMB_INTENSITY,         "AmbIntensity"},
      {MDLTOK_AMBIENT,              "Ambient"},
      {MDLTOK_ANIM,                 "Anim"},
      {MDLTOK_ANIMATIONFILE,        "AnimationFile"},
      {MDLTOK_ATTACHMENTID,         "AttachmentID"},
      {MDLTOK_ATTENUATION,          "Attenuation"},
      {MDLTOK_ATTENUATIONSTART,     "AttenuationStart"},
      {MDLTOK_ATTENUATIONEND,       "AttenuationEnd"},
      {MDLTOK_BEZIER,               "Bezier"},
      {MDLTOK_BILLBOARD,          "Billboarded"},
      {MDLTOK_BILLBOARD_LOCK_X,     "BillboardedLockX"},
      {MDLTOK_BILLBOARD_LOCK_Y,     "BillboardedLockY"},
      {MDLTOK_BILLBOARD_LOCK_Z,     "BillboardedLockZ"},
      {MDLTOK_BITMAP,               "Bitmap"},
      {MDLTOK_BLEND,                "Blend"},
      {MDLTOK_BLEND_COLORS,          "BlendColors"},
      {MDLTOK_BLEND_TIME,            "BlendTime"},
      {MDLTOK_BONE_INDICES,          "BoneIndices"},
      {MDLTOK_BONE_WEIGHTS,          "BoneWeights"},
      {MDLTOK_BOTH,                 "Both"},
      {MDLTOK_BOUNDS_RADIUS,         "BoundsRadius"},
      {MDLTOK_BOX,                  "Box"},
      {MDLTOK_COLOR,                "Color"},
      {MDLTOK_COLS,              "Columns"},
      {MDLTOK_COMPONENT_SKIN,        "ComponentSkin"},
      {MDLTOK_CONNECT,              "Connect"},
      {MDLTOK_CONSTANTCOLOR,        "ConstantColor"},
      {MDLTOK_COORD_ID,              "CoordId"},
      {MDLTOK_CYLINDER,             "Cylinder"},
      {MDLTOK_DECAY_UV,          "DecayUVAnim"},
      {MDLTOK_DIRECTIONAL,          "Directional"},
      {MDLTOK_DONTINHERIT,          "DontInherit"},
      {MDLTOK_DONTINTERP,           "DontInterp"},
      {MDLTOK_DRAG,                 "Drag"},
      {MDLTOK_DUPLICATES,           "Duplicates"},
      {MDLTOK_DURATION,             "Duration"},
      {MDLTOK_EMISSION_RATE,         "EmissionRate"},
      {MDLTOK_EMITTER_USES_MDL,       "EmitterUsesMDL"},
      {MDLTOK_EMITTER_USES_TGA,       "EmitterUsesTGA"},
      {MDLTOK_EVENT_TRACK,           "EventTrack"},
      {MDLTOK_FACES,                "Faces"},
      {MDLTOK_FAR_CLIP,              "FarClip"},
      {MDLTOK_FIELDOFVIEW,          "FieldOfView"},
      {MDLTOK_FILTERMODE,           "FilterMode"},
      {MDLTOK_FORMATVERSION,        "FormatVersion"},
      {MDLTOK_FPS,                  "FPS"},
      {MDLTOK_FREQUENCY,            "Frequency"},
      {MDLTOK_FULLRESOLUTION,       "FullResolution"},
      {MDLTOK_GEOSETID,             "GeosetId"},
      {MDLTOK_GEOSETANIMID,         "GeosetAnimId"},
      {MDLTOK_GLOBALSEQID,          "GlobalSeqId"},
      {MDLTOK_GRAVITY,              "Gravity"},
      {MDLTOK_GROUNDTRACK,          "GroundTrack"},
      {MDLTOK_GROUP,                "Group"},
      {MDLTOK_GROUPS,               "Groups"},
      {MDLTOK_HEAD,                 "Head"},
      {MDLTOK_HEIGHT,               "Height"},
      {MDLTOK_HEIGHT_ABOVE,          "HeightAbove"},
      {MDLTOK_HEIGHT_BELOW,          "HeightBelow"},
      {MDLTOK_HERMITE,              "Hermite"},
      {MDLTOK_IMAGE,                "Image"},
      {MDLTOK_INIT_VELOCITY,         "InitVelocity"},
      {MDLTOK_INTAN,                "InTan"},
      {MDLTOK_INTENSITY,            "Intensity"},
      {MDLTOK_INTERVAL,             "Interval"},
      {MDLTOK_LATITUDE,             "Latitude"},
      {MDLTOK_LONGITUDE,            "Longitude"},
      {MDLTOK_LAYER,                "Layer"},
      {MDLTOK_LENGTH,               "Length"},
      {MDLTOK_LIFESPAN,             "LifeSpan"},
      {MDLTOK_LIFESPAN_UV,       "LifeSpanUVAnim"},
      {MDLTOK_LINEAR,               "Linear"},
      {MDLTOK_LINES,                "Lines"},
      {MDLTOK_LINE_EMITTER,          "LineEmitter"},
      {MDLTOK_LINE_LOOP,             "LineLoop"},
      {MDLTOK_LINE_STRIP,            "LineStrip"},
      {MDLTOK_MATERIAL,             "Material"},
      {MDLTOK_MATERIAL_ID,           "MaterialID"},
      {MDLTOK_MATRICES,             "Matrices"},
      {MDLTOK_MAXIMUMEXTENT,        "MaximumExtent"},
      {MDLTOK_MINIMUMEXTENT,        "MinimumExtent"},
      {MDLTOK_MODEL_SPACE,           "ModelSpace"},
      {MDLTOK_MODULATE,             "Modulate"},
      {MDLTOK_MODULATE2X,           "Modulate2x"},
      {MDLTOK_MOVESPEED,            "MoveSpeed"},
      {MDLTOK_MULTIPLE,             "Multiple"},
      {MDLTOK_NEAR_CLIP,             "NearClip"},
      {MDLTOK_NO_DEPTH_TEST,          "NoDepthTest"},
      {MDLTOK_NO_DEPTH_SET,           "NoDepthSet"},
      {MDLTOK_CAPNONE,                 "None"},
      {MDLTOK_NONLOOPING,           "NonLooping"},
      {MDLTOK_NORMALS,              "Normals"},
      {MDLTOK_NUMATTACHMENTS,       "NumAttachments"},
      {MDLTOK_NUMBONES,             "NumBones"},
      {MDLTOK_NUMEVENTS,            "NumEvents"},
      {MDLTOK_NUMGEOSETS,           "NumGeosets"},
      {MDLTOK_NUMGEOSETANIMS,       "NumGeosetAnims"},
      {MDLTOK_NUMHELPERS,           "NumHelpers"},
      {MDLTOK_NUMLIGHTS,            "NumLights"},
      {MDLTOK_NUMMESHES,            "NumMeshes"},
      {MDLTOK_NUMPARTICLEEMITTERS,  "NumParticleEmitters"},
      {MDLTOK_NUMPARTICLEEMITTERS2, "NumParticleEmitters2"},
      {MDLTOK_NUMRIBBONEMITTERS,    "NumRibbonEmitters"},
      {MDLTOK_OBJECTID,             "ObjectId"},
      {MDLTOK_OMNIDIRECTIONAL,      "Omnidirectional"},
      {MDLTOK_OPACITY,              "Opacity"},
      {MDLTOK_OUTTAN,               "OutTan"},
      {MDLTOK_PARENT,               "Parent"},
      {MDLTOK_PARTICLE,             "Particle"},
      {MDLTOK_PARTICLE_0XKILL,       "Particle0XKill"},
      {MDLTOK_PARTICLE_EXTRUDE,      "ParticleExtrude"},
      {MDLTOK_PARTICLE_FOLLOW,       "ParticleFollow"},
      {MDLTOK_PARTICLE_FOLLOW_PARAMS, "ParticleFollowParams"},
      {MDLTOK_PARTICLE_INHERIT_SCALE, "ParticleInheritScale"},
      {MDLTOK_PARTICLE_IVEL_LIN,      "ParticleIVelLin"},
      {MDLTOK_PARTICLE_IVEL_SCALE,    "ParticleIVelScale"},
      {MDLTOK_PARTICLE_GEOMETRY_MDL,  "ParticleGeometryMdl"},
      {MDLTOK_PARTICLE_PROJECT,      "ParticleProject"},
      {MDLTOK_PARTICLE_RECURSION_MDL, "ParticleRecursionMdl"},
      {MDLTOK_PARTICLE_ROTATION,     "ParticleRotation"},
      {MDLTOK_PARTICLE_SCALING,      "ParticleScaling"},
      {MDLTOK_PARTICLE_TUMBLE,       "ParticleTumble"},
      {MDLTOK_PARTICLE_TUMBLER,      "ParticleTumbleR"},
      {MDLTOK_PARTICLE_TWINKLE_ONOFF, "ParticleTwinkleOnOff"},
      {MDLTOK_PARTICLE_TWINKLE_SCALE, "ParticleTwinkleScale"},
      {MDLTOK_PARTICLE_XYQUADS,      "ParticleXYQuads"},
      {MDLTOK_PARTICLE_ZSOURCE,      "ParticleZSource"},
      {MDLTOK_PARTICLE_ZVEL_ONLY,     "ParticleZVelOnly"},
      {MDLTOK_PATH,                 "Path"},
      {MDLTOK_PITCH,                "Pitch"},
      {MDLTOK_PLANE,                "Plane"},
      {MDLTOK_POINTS,               "Points"},
      {MDLTOK_POLYGON,             "Polygons"},
      {MDLTOK_POSITION,             "Position"},
      {MDLTOK_PRIORITYPLANE,        "PriorityPlane"},
      {MDLTOK_PROJECT,              "Project"},
      {MDLTOK_QUADS,                "Quads"},
      {MDLTOK_QUAD_STRIP,            "QuadStrip"},
      {MDLTOK_REPLACEABLE_ID,        "ReplaceableId"},
      {MDLTOK_REPLAY,               "Replay"},
      {MDLTOK_ROLL,                 "Roll"},
      {MDLTOK_ROTATION,             "Rotation"},
      {MDLTOK_ROWS,                 "Rows"},
      {MDLTOK_SCALING,              "Scaling"},
      {MDLTOK_SEGMENT_COLOR,         "SegmentColor"},
      {MDLTOK_SELECTION_GROUP,       "SelectionGroup"},
      {MDLTOK_SNDMAXDIST,      "MaximumDistance"},
      {MDLTOK_SNDMINDIST,      "MinimumDistance"},
      {MDLTOK_SPHERE,               "Sphere"},
      {MDLTOK_SPHERE_ENV_MAP,         "SphereEnvMap"},
      {MDLTOK_SPLINE,               "Spline"},
      {MDLTOK_SORTPRIMSFARZ,        "SortPrimsFarZ"},
      {MDLTOK_SORTPRIMSNEARZ,       "SortPrimsNearZ"},
      {MDLTOK_SPEED,                "Speed"},
      {MDLTOK_SQUIRT,               "Squirt"},
      {MDLTOK_STATIC,               "static"},
      {MDLTOK_TAIL,                 "Tail"},
      {MDLTOK_TAIL_GROWS,            "TailGrows"},
      {MDLTOK_TAIL_LENGTH,           "TailLength"},
      {MDLTOK_TAIL_DECAY_UV,      "TailDecayUVAnim"},
      {MDLTOK_TAIL_UV,           "TailUVAnim"},
      {MDLTOK_TARGET,               "Target"},
      {MDLTOK_TEAM_COLOR,            "TeamColor"},
      {MDLTOK_TEXTURE_ID,            "TextureID"},
      {MDLTOK_TEXTURE_SLOT,          "TextureSlot"},
      {MDLTOK_TFACES,               "TFaces"},
      {MDLTOK_TIME,                 "Time"},
      {MDLTOK_TRANSLATION,          "Translation"},
      {MDLTOK_TRANSPARENT,          "Transparent"},
      {MDLTOK_TRIANGLES,            "Triangles"},
      {MDLTOK_TRIANGLE_FAN,          "TriangleFan"},
      {MDLTOK_TRIANGLE_STRIP,        "TriangleStrip"},
      {MDLTOK_TVERTEXANIM,          "TVertexAnim"},
      {MDLTOK_TVERTEXANIMID,        "TVertexAnimId"},
      {MDLTOK_TVERTICES,            "TVertices"},
      {MDLTOK_TWO_SIDED,             "TwoSided"},
      {MDLTOK_TYPE,                 "Type"},
      {MDLTOK_UNFOGGED,             "Unfogged"},
      {MDLTOK_UNSELECTABLE,         "Unselectable"},
      {MDLTOK_UNSHADED,             "Unshaded"},
      {MDLTOK_VARIATION,            "Variation"},
      {MDLTOK_VERTEX,               "Vertex"},
      {MDLTOK_VERTEXCOUNT,          "VertexCount"},
      {MDLTOK_VERTEX_GROUP,          "VertexGroup"},
      {MDLTOK_VERTICES,             "Vertices"},
      {MDLTOK_VISIBILITY,           "Visibility"},
      {MDLTOK_WIDTH,                "Width"},
      {MDLTOK_WIND,                 "Wind"},
      {MDLTOK_WRAPHEIGHT,           "WrapHeight"},
      {MDLTOK_WRAPWIDTH,            "WrapWidth"},
      {MDLTOK_YAW,                  "Yaw"},
      {MDLTOK_UNKNOWN,              "Unknown"}
};

namespace MDL {

  static char s_singletoktbl[256][2];

  void InitializeTokenText() {
    UINT index = 256;

    do {
      --index;
      s_singletoktbl[index][0] = index;
    } while (index);
  }

  void DestroyTokenText() {
  }

  LPCSTR TokenText(UINT token) {
    if (token < MDLTOK_FIRST_TOKEN) {
      return s_singletoktbl[token];
    }
    if (token > 479) {
      token = token & 0x80000000 ? 0 : 479;
      if (token < MDLTOK_FIRST_TOKEN) {
        return s_singletoktbl[token];
      }
    }
    FATALASSERT(s_tokentext[token - MDLTOK_FIRST_TOKEN].token == token);
    return s_tokentext[token - MDLTOK_FIRST_TOKEN].text;
  }

}  // namespace MDL
