#include <Base/Base.h>

namespace MDL {

  static char s_singletoktbl[256][2];
  static const struct {
    UINT   token;
    LPCSTR text;
  } s_tokentext[224] = {
      {0x100,         "Literal Long"},
      {0x101,        "Literal Float"},
      {0x102,       "Literal String"},
      {0x103,              "Version"},
      {0x104,                "Model"},
      {0x105,            "Sequences"},
      {0x106,      "GlobalSequences"},
      {0x107,         "TextureAnims"},
      {0x108,             "Textures"},
      {0x109,            "Materials"},
      {0x10A,               "Geoset"},
      {0x10B,           "GeosetAnim"},
      {0x10C,                 "Bone"},
      {0x10D,                 "Mesh"},
      {0x10E,                "Light"},
      {0x10F,               "Helper"},
      {0x110,           "Attachment"},
      {0x111,          "PivotPoints"},
      {0x112,      "ParticleEmitter"},
      {0x113,     "ParticleEmitter2"},
      {0x114,               "Camera"},
      {0x115,          "EventObject"},
      {0x116,         "HitTestShape"},
      {0x117,       "CollisionShape"},
      {0x118,        "RibbonEmitter"},
      {0x119,            "Collision"},
      {0x11A,             "Additive"},
      {0x11B,             "AddAlpha"},
      {0x11C,                "Alpha"},
      {0x11D,             "AlphaKey"},
      {0x11E,        "AlwaysAnimate"},
      {0x11F,             "AmbColor"},
      {0x120,         "AmbIntensity"},
      {0x121,              "Ambient"},
      {0x122,                 "Anim"},
      {0x123,        "AnimationFile"},
      {0x124,         "AttachmentID"},
      {0x125,          "Attenuation"},
      {0x126,     "AttenuationStart"},
      {0x127,       "AttenuationEnd"},
      {0x128,               "Bezier"},
      {0x129,          "Billboarded"},
      {0x12A,     "BillboardedLockX"},
      {0x12B,     "BillboardedLockY"},
      {0x12C,     "BillboardedLockZ"},
      {0x12D,               "Bitmap"},
      {0x12E,                "Blend"},
      {0x12F,          "BlendColors"},
      {0x130,            "BlendTime"},
      {0x131,          "BoneIndices"},
      {0x132,          "BoneWeights"},
      {0x133,                 "Both"},
      {0x134,         "BoundsRadius"},
      {0x135,                  "Box"},
      {0x136,                "Color"},
      {0x137,              "Columns"},
      {0x138,        "ComponentSkin"},
      {0x139,              "Connect"},
      {0x13A,        "ConstantColor"},
      {0x13B,              "CoordId"},
      {0x13C,             "Cylinder"},
      {0x13D,          "DecayUVAnim"},
      {0x13E,          "Directional"},
      {0x13F,          "DontInherit"},
      {0x140,           "DontInterp"},
      {0x141,                 "Drag"},
      {0x142,           "Duplicates"},
      {0x143,             "Duration"},
      {0x144,         "EmissionRate"},
      {0x145,       "EmitterUsesMDL"},
      {0x146,       "EmitterUsesTGA"},
      {0x147,           "EventTrack"},
      {0x148,                "Faces"},
      {0x149,              "FarClip"},
      {0x14A,          "FieldOfView"},
      {0x14B,           "FilterMode"},
      {0x14C,        "FormatVersion"},
      {0x14D,                  "FPS"},
      {0x14E,            "Frequency"},
      {0x14F,       "FullResolution"},
      {0x150,             "GeosetId"},
      {0x151,         "GeosetAnimId"},
      {0x152,          "GlobalSeqId"},
      {0x153,              "Gravity"},
      {0x154,          "GroundTrack"},
      {0x155,                "Group"},
      {0x156,               "Groups"},
      {0x157,                 "Head"},
      {0x158,               "Height"},
      {0x159,          "HeightAbove"},
      {0x15A,          "HeightBelow"},
      {0x15B,              "Hermite"},
      {0x15C,                "Image"},
      {0x15D,         "InitVelocity"},
      {0x15E,                "InTan"},
      {0x15F,            "Intensity"},
      {0x160,             "Interval"},
      {0x161,             "Latitude"},
      {0x162,            "Longitude"},
      {0x163,                "Layer"},
      {0x164,               "Length"},
      {0x165,             "LifeSpan"},
      {0x166,       "LifeSpanUVAnim"},
      {0x167,               "Linear"},
      {0x168,                "Lines"},
      {0x169,          "LineEmitter"},
      {0x16A,             "LineLoop"},
      {0x16B,            "LineStrip"},
      {0x16C,             "Material"},
      {0x16D,           "MaterialID"},
      {0x16E,             "Matrices"},
      {0x16F,        "MaximumExtent"},
      {0x170,        "MinimumExtent"},
      {0x171,           "ModelSpace"},
      {0x172,             "Modulate"},
      {0x173,           "Modulate2x"},
      {0x174,            "MoveSpeed"},
      {0x175,             "Multiple"},
      {0x176,             "NearClip"},
      {0x177,          "NoDepthTest"},
      {0x178,           "NoDepthSet"},
      {0x179,                 "None"},
      {0x17A,           "NonLooping"},
      {0x17B,              "Normals"},
      {0x17C,       "NumAttachments"},
      {0x17D,             "NumBones"},
      {0x17E,            "NumEvents"},
      {0x17F,           "NumGeosets"},
      {0x180,       "NumGeosetAnims"},
      {0x181,           "NumHelpers"},
      {0x182,            "NumLights"},
      {0x183,            "NumMeshes"},
      {0x184,  "NumParticleEmitters"},
      {0x185, "NumParticleEmitters2"},
      {0x186,    "NumRibbonEmitters"},
      {0x187,             "ObjectId"},
      {0x188,      "Omnidirectional"},
      {0x189,              "Opacity"},
      {0x18A,               "OutTan"},
      {0x18B,               "Parent"},
      {0x18C,             "Particle"},
      {0x18D,       "Particle0XKill"},
      {0x18E,      "ParticleExtrude"},
      {0x18F,       "ParticleFollow"},
      {0x190, "ParticleFollowParams"},
      {0x191, "ParticleInheritScale"},
      {0x192,      "ParticleIVelLin"},
      {0x193,    "ParticleIVelScale"},
      {0x194,  "ParticleGeometryMdl"},
      {0x195,      "ParticleProject"},
      {0x196, "ParticleRecursionMdl"},
      {0x197,     "ParticleRotation"},
      {0x198,      "ParticleScaling"},
      {0x199,       "ParticleTumble"},
      {0x19A,      "ParticleTumbleR"},
      {0x19B, "ParticleTwinkleOnOff"},
      {0x19C, "ParticleTwinkleScale"},
      {0x19D,      "ParticleXYQuads"},
      {0x19E,      "ParticleZSource"},
      {0x19F,     "ParticleZVelOnly"},
      {0x1A0,                 "Path"},
      {0x1A1,                "Pitch"},
      {0x1A2,                "Plane"},
      {0x1A3,               "Points"},
      {0x1A4,             "Polygons"},
      {0x1A5,             "Position"},
      {0x1A6,        "PriorityPlane"},
      {0x1A7,              "Project"},
      {0x1A8,                "Quads"},
      {0x1A9,            "QuadStrip"},
      {0x1AA,        "ReplaceableId"},
      {0x1AB,               "Replay"},
      {0x1AC,                 "Roll"},
      {0x1AD,             "Rotation"},
      {0x1AE,                 "Rows"},
      {0x1AF,              "Scaling"},
      {0x1B0,         "SegmentColor"},
      {0x1B1,       "SelectionGroup"},
      {0x1B2,      "MaximumDistance"},
      {0x1B3,      "MinimumDistance"},
      {0x1B4,               "Sphere"},
      {0x1B5,         "SphereEnvMap"},
      {0x1B6,               "Spline"},
      {0x1B7,        "SortPrimsFarZ"},
      {0x1B8,       "SortPrimsNearZ"},
      {0x1B9,                "Speed"},
      {0x1BA,               "Squirt"},
      {0x1BB,               "static"},
      {0x1BC,                 "Tail"},
      {0x1BD,            "TailGrows"},
      {0x1BE,           "TailLength"},
      {0x1BF,      "TailDecayUVAnim"},
      {0x1C0,           "TailUVAnim"},
      {0x1C1,               "Target"},
      {0x1C2,            "TeamColor"},
      {0x1C3,            "TextureID"},
      {0x1C4,          "TextureSlot"},
      {0x1C5,               "TFaces"},
      {0x1C6,                 "Time"},
      {0x1C7,          "Translation"},
      {0x1C8,          "Transparent"},
      {0x1C9,            "Triangles"},
      {0x1CA,          "TriangleFan"},
      {0x1CB,        "TriangleStrip"},
      {0x1CC,          "TVertexAnim"},
      {0x1CD,        "TVertexAnimId"},
      {0x1CE,            "TVertices"},
      {0x1CF,             "TwoSided"},
      {0x1D0,                 "Type"},
      {0x1D1,             "Unfogged"},
      {0x1D2,         "Unselectable"},
      {0x1D3,             "Unshaded"},
      {0x1D4,            "Variation"},
      {0x1D5,               "Vertex"},
      {0x1D6,          "VertexCount"},
      {0x1D7,          "VertexGroup"},
      {0x1D8,             "Vertices"},
      {0x1D9,           "Visibility"},
      {0x1DA,                "Width"},
      {0x1DB,                 "Wind"},
      {0x1DC,           "WrapHeight"},
      {0x1DD,            "WrapWidth"},
      {0x1DE,                  "Yaw"},
      {0x1DF,              "Unknown"}
  };

  void InitializeTokenText() {
    UINT index = 256;

    do {
      --index;
      s_singletoktbl[index][0] = static_cast<char>(index);
    } while (index);
  }

  void DestroyTokenText() {
  }

  LPCSTR TokenText(UINT token) {
    if (token < 256) {
      return s_singletoktbl[token];
    }
    if (token > 479) {
      token = token & 0x80000000 ? 0 : 479;
      if (token < 256) {
        return s_singletoktbl[token];
      }
    }
    FATALASSERT(s_tokentext[token - 256].token == token);
    return s_tokentext[token - 256].text;
  }

}  // namespace MDL
