// SErrSetLogCallback
// SErrGetLogLastPath
// SErrPrepareAppFatal
// SErrDisplayAppFatal
// SErrSetLastError
// SErrDisplayError
// SErrDisplayErrorFmt
// SErrGetErrorStr
// SErrGetLastError
// SErrIsDisplayingError
// SErrCatchUnhandledExceptions
// SErrReportResourceLeak
// SErrReportNamedResourceLeak
// SErrSetLogTitleString
// SErrSetAppCommand
// SErrInitialize
// SErrDestroy
// SErrRegisterHandler
// SErrMacSetAssertOptions
// SErrMacGetAssertOptions
