add_library(DBClient STATIC
    AutoCode/AreaMIDIAmbiencesRec.cpp
    AutoCode/AreaPOIRec.cpp
    AutoCode/AreaTableRec.cpp
    AutoCode/AreaTriggerRec.cpp
    AutoCode/AttackAnimKitsRec.cpp
    AutoCode/AttackAnimTypesRec.cpp
    AutoCode/BankBagSlotPricesRec.cpp
    AutoCode/CameraShakesRec.cpp
    AutoCode/CharacterCreateCamerasRec.cpp
    AutoCode/CharacterFacialHairStylesRec.cpp
    AutoCode/CharBaseInfoRec.cpp
    AutoCode/CharHairGeosetsRec.cpp
    AutoCode/CharStartOutfitRec.cpp
    AutoCode/CharTextureVariationsV2Rec.cpp
    AutoCode/CharVariationsRec.cpp
    AutoCode/ChrClassesRec.cpp
    AutoCode/ChrProficiencyRec.cpp
    AutoCode/ChrRacesRec.cpp
    AutoCode/CinematicCameraRec.cpp
    AutoCode/CinematicSequencesRec.cpp
    AutoCode/CreatureDisplayInfoExtraRec.cpp
    AutoCode/CreatureDisplayInfoRec.cpp
    AutoCode/CreatureFamilyRec.cpp
    AutoCode/CreatureModelDataRec.cpp
    AutoCode/CreatureSoundDataRec.cpp
    AutoCode/CreatureTypeRec.cpp
    DBCache.cpp
    DBCacheInstances.cpp
    DBClient.cpp
    AutoCode/DeathThudLookupsRec.cpp
    AutoCode/EmoteAnimsRec.cpp
    AutoCode/EmotesRec.cpp
    AutoCode/EmotesTextDataRec.cpp
    AutoCode/EmotesTextRec.cpp
    AutoCode/FactionGroupRec.cpp
    AutoCode/FactionRec.cpp
    AutoCode/FactionTemplateRec.cpp
    AutoCode/FootprintTexturesRec.cpp
    AutoCode/FootstepTerrainLookupRec.cpp
    AutoCode/GameObjectDisplayInfoRec.cpp
    AutoCode/GroundEffectDoodadRec.cpp
    AutoCode/GroundEffectTextureRec.cpp
    AutoCode/HelmetGeosetVisDataRec.cpp
    AutoCode/ItemClassRec.cpp
    AutoCode/ItemDisplayInfoRec.cpp
    AutoCode/ItemGroupSoundsRec.cpp
    AutoCode/ItemSubClassRec.cpp
    AutoCode/ItemVisualEffectsRec.cpp
    AutoCode/ItemVisualsRec.cpp
    AutoCode/LanguagesRec.cpp
    AutoCode/LanguageWordsRec.cpp
    AutoCode/LockRec.cpp
    AutoCode/LockTypeRec.cpp
    AutoCode/MapRec.cpp
    AutoCode/MaterialRec.cpp
    AutoCode/NamesProfanityRec.cpp
    AutoCode/NamesReservedRec.cpp
    AutoCode/NPCSoundsRec.cpp
    AutoCode/PageTextMaterialRec.cpp
    AutoCode/PaperDollItemFrameRec.cpp
    AutoCode/QuestInfoRec.cpp
    AutoCode/QuestSortRec.cpp
    AutoCode/ResistancesRec.cpp
    sdbItemSubclass.cpp
    sdbWMOAreaTable.cpp
    AutoCode/SheatheSoundLookupsRec.cpp
    AutoCode/SkillLineAbilityRec.cpp
    AutoCode/SkillLineRec.cpp
    AutoCode/SoundCharacterMacroLinesRec.cpp
    AutoCode/SoundEntriesRec.cpp
    AutoCode/SoundProviderPreferencesRec.cpp
    AutoCode/SoundSamplePreferencesRec.cpp
    AutoCode/SoundWaterTypeRec.cpp
    AutoCode/SpellAuraNamesRec.cpp
    AutoCode/SpellCastTimesRec.cpp
    AutoCode/SpellChainEffectsRec.cpp
    AutoCode/SpellDispelTypeRec.cpp
    AutoCode/SpellDurationRec.cpp
    AutoCode/SpellEffectCameraShakesRec.cpp
    AutoCode/SpellEffectNamesRec.cpp
    AutoCode/SpellFocusObjectRec.cpp
    AutoCode/SpellIconRec.cpp
    AutoCode/SpellItemEnchantmentRec.cpp
    AutoCode/SpellRadiusRec.cpp
    AutoCode/SpellRangeRec.cpp
    AutoCode/SpellRec.cpp
    AutoCode/SpellShapeshiftFormRec.cpp
    AutoCode/SpellVisualAnimNameRec.cpp
    AutoCode/SpellVisualEffectNameRec.cpp
    AutoCode/SpellVisualKitRec.cpp
    AutoCode/SpellVisualPrecastTransitionsRec.cpp
    AutoCode/SpellVisualRec.cpp
    StatConstants.cpp
    AutoCode/StringLookupsRec.cpp
    AutoCode/TabardBackgroundTexturesRec.cpp
    AutoCode/TabardEmblemTexturesRec.cpp
    AutoCode/TaxiNodesRec.cpp
    AutoCode/TaxiPathNodeRec.cpp
    AutoCode/TaxiPathRec.cpp
    AutoCode/TerrainTypeRec.cpp
    AutoCode/TerrainTypeSoundsRec.cpp
    AutoCode/TransportAnimationRec.cpp
    AutoCode/UISoundLookupsRec.cpp
    AutoCode/UnitBloodLevelsRec.cpp
    AutoCode/UnitBloodRec.cpp
    AutoCode/VocalUISoundsRec.cpp
    AutoCode/WeaponImpactSoundsRec.cpp
    AutoCode/WeaponSwingSounds2Rec.cpp
    AutoCode/WMOAreaTableRec.cpp
    AutoCode/WorldMapAreaRec.cpp
    AutoCode/WorldMapContinentRec.cpp
    AutoCode/WorldSafeLocsRec.cpp
    AutoCode/ZoneMusicRec.cpp
)

target_include_directories(DBClient PRIVATE
    ../..
    ../../../../Engine/Source
    ../../../../Storm/H

    ../../../Common
)

if(MSVC_VERSION EQUAL 1200)
    target_compile_options(DBClient PRIVATE /Gr /Z7)
endif()
