#pragma once

static const float MAX_DUEL_DISTANCE = 10.0f;
static const float MAX_DUEL_DISTANCE_SQUARED = MAX_DUEL_DISTANCE * MAX_DUEL_DISTANCE;
static const float MAX_TRADE_DISTANCE = 11.111111f;
static const float MAX_TRADE_DISTANCE_SQUARED = MAX_TRADE_DISTANCE * MAX_TRADE_DISTANCE;
static const float MAX_SHOP_DISTANCE = 5.5555553f;
static const float MAX_SHOP_DISTANCE_SQUARED = MAX_SHOP_DISTANCE * MAX_SHOP_DISTANCE;
static const float MAX_INSPECT_DISTANCE = 5.5555553f;
static const float MAX_INSPECT_DISTANCE_SQUARED = MAX_INSPECT_DISTANCE * MAX_INSPECT_DISTANCE;
static const float MAX_LOOT_DISTANCE = 5.0f;
static const float MAX_LOOT_DISTANCE_SQUARED = MAX_LOOT_DISTANCE * MAX_LOOT_DISTANCE;
static const float MAX_BIND_DISTANCE = 10.0f;
static const float MAX_BIND_DISTANCE_SQUARED = MAX_BIND_DISTANCE * MAX_BIND_DISTANCE;
static const float MAX_SITCHAIR_DISTANCE = 0.5f;
static const float MAX_SITCHAIR_DISTANCE_SQUARED = MAX_SITCHAIR_DISTANCE * MAX_SITCHAIR_DISTANCE;
static const float MAX_SITCHAIRUSE_DISTANCE = 3.0f;
static const float MAX_SITCHAIRUSE_DISTANCE_SQUARED = MAX_SITCHAIRUSE_DISTANCE * MAX_SITCHAIRUSE_DISTANCE;
static const float MAX_SHARE_DISTANCE = 100.0f;
static const float MAX_SHARE_DISTANCE_SQUARED = MAX_SHARE_DISTANCE * MAX_SHARE_DISTANCE;
static const float SECONDS_PER_HEARTBEAT = 5000.0f / 1000.0f;
static const float SPELL_FOCUS_DISTANCE = 50.0f;
static const float SPELL_FOCUS_DISTANCE_SQUARED = SPELL_FOCUS_DISTANCE * SPELL_FOCUS_DISTANCE;
static const float MAX_OBJ_INTEREST_RADIUS = 100.0f;
static const float MAX_OBJ_INTEREST_RADIUS_SQUARED = MAX_OBJ_INTEREST_RADIUS * MAX_OBJ_INTEREST_RADIUS;

enum INVENTORY_TYPES {
  INDEX_NON_EQUIP_TYPE = 0,
  INDEX_HEAD_TYPE = 1,
  INDEX_NECK_TYPE = 2,
  INDEX_SHOULDER_TYPE = 3,
  INDEX_BODY_TYPE = 4,
  INDEX_CHEST_TYPE = 5,
  INDEX_WAIST_TYPE = 6,
  INDEX_LEGS_TYPE = 7,
  INDEX_FEET_TYPE = 8,
  INDEX_WRIST_TYPE = 9,
  INDEX_HAND_TYPE = 10,
  INDEX_FINGER_TYPE = 11,
  INDEX_TRINKET_TYPE = 12,
  INDEX_WEAPON_TYPE = 13,
  INDEX_SHIELD_TYPE = 14,
  INDEX_RANGED_TYPE = 15,
  INDEX_CLOAK_TYPE = 16,
  INDEX_2HWEAPON_TYPE = 17,
  INDEX_BAG_TYPE = 18,
  INDEX_TABARD_TYPE = 19,
  INDEX_ROBE_TYPE = 20,
  INDEX_WEAPONMAINHAND_TYPE = 21,
  INDEX_WEAPONOFFHAND_TYPE = 22,
  INDEX_HOLDABLE_TYPE = 23,
  INDEX_AMMO_TYPE = 24,
  INDEX_THROWN_TYPE = 25,
  INDEX_RANGEDRIGHT_TYPE = 26,
  INDEX_NUMSLOTS = 27,
  INDEX_INVALID_INVENTORYTYPE = 28
};
